version: '3.8'

services:
  meu-mongo:
    image: mongo:latest
    container_name: container-mongo
    ports:
      - "27017:27017"
    volumes:
      - dados-do-banco:/data/db
    
  backend:
    build: ./treino
    container_name: container-backend
    ports:
      - "3000:3000"
    depends_on: 
      - meu-mongo
    environment:
      - MONGO_URI=mongodb://meu-mongo:27017/tarefas-db
    env_file:
      - ./treino/.env

  frontend:
    build: ./interface/tela
    container_name: container-frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  dados-do-banco: